COMPONENT = TestC
CFLAGS += -DCC2420_DEF_RFPOWER=31
CFLAGS += -DCC2420_DEF_CHANNEL=18
CFLAGS += -DPACKET_LINK
#CFLAGS += -DLOW_POWER_LISTENING
CFLAGS += -DCC2420_HW_ACKNOWLEDGEMENTS 
CFLAGS += -DCC2420_HW_ADDRESS_RECOGNITION
CFLAGS += -DTOSH_DATA_LENGTH=30

CFLAGS += -I$(TINYOS_ROOT_DIR)/tos/lib/printf
CFLAGS += -DNEW_PRINTF_SEMANTICS

#Define slotted transmission timing
CFLAGS += -DSLOT_DURATION=32768L/10
CFLAGS += -DMAX_SLAVES=10


include $(TINYOS_ROOT_DIR)/Makefile.include

